[patch.crates-io]
shuttle-proto = { git = "https://github.com/Samarth1696/shuttle.git" }
shuttle-runtime = { git = "https://github.com/Samarth1696/shuttle.git" }
shuttle-service = { git = "https://github.com/Samarth1696/shuttle.git" }